version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine  # Versión ligera
    ports:
      - "6379:6379"  # Expone puerto local
    volumes:
      - redis_data:/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # Puerto SMTP
      - "8025:8025"  # Interfaz web para ver correos
volumes:
  postgres_data:
  redis_data: